"""Phase 8 — replacement for the deleted post_intake_issues machinery.

This module provides the small, well-defined replacement surface that
the convergence runner, cash runner, contracts runner, state runner,
and convergence runtime now consume. The legacy issue ledger / issue
status records / controller_resolution_state are gone — the realism
gate (post_intake_realism), cascade diagnostics
(post_intake_solver.adaptation_cascade), and planning_mode_policy
(post_intake_realism.lookup) are the new authority.

Function names mirror the legacy bound names so the call-site changes
are minimal: callers replace
``from <bind injection> _build_realism_memo_from_issue_ledger``
with
``from client_intake_and_finmo.post_intake_resolution_state import
  build_realism_memo``.
The dict shapes the functions return remain compatible with what the
existing planning_run_json / realism_memo_json schemas expect, so
downstream readers (workbook export, planning_runtime_json) still work.
"""

from __future__ import annotations

from client_intake_and_finmo.post_intake_resolution_state.state import (  # type: ignore
  build_controller_resolution_state,
  build_persisted_realism_memo_payload,
  build_realism_memo,
  build_resolution_summary,
  empty_controller_resolution_state,
  empty_realism_memo,
  empty_resolution_summary,
  filter_cash_pass_owned_issue_records,
  financial_story_issue_codes,
  issue_status_records_from_state,
  realism_gate_hard_fail_count,
  realism_gate_hard_fail_metric_keys,
)
from client_intake_and_finmo.post_intake_resolution_state import legacy_compat  # type: ignore  # noqa: F401


def bind_runtime_dependencies(dependencies):
  """Phase 8 — provider hook for the binding system. The replacement
  functions are pure (no runtime injection needed); this hook exists
  so the dependency-provider list in intake_consult.py can include
  this module without special-casing it."""
  return None


__all__ = [
  "bind_runtime_dependencies",
  "build_controller_resolution_state",
  "build_persisted_realism_memo_payload",
  "build_realism_memo",
  "build_resolution_summary",
  "empty_controller_resolution_state",
  "empty_realism_memo",
  "empty_resolution_summary",
  "filter_cash_pass_owned_issue_records",
  "financial_story_issue_codes",
  "issue_status_records_from_state",
  "realism_gate_hard_fail_count",
  "realism_gate_hard_fail_metric_keys",
  # Legacy bound names — see legacy_compat.py for the wrappers that
  # adapt the new signatures to the old call-sites.
  "_build_controller_resolution_state_from_issue_ledger",
  "_build_realism_memo_from_issue_ledger",
  "_build_resolution_summary_from_issue_ledger",
  "_apply_realism_verification_to_issue_status_records",
  "_controller_state_issue_status_records",
  "_build_persisted_realism_memo_payload",
  "_financial_story_issue_codes",
  "_filter_cash_pass_owned_issue_records",
  "_merge_new_scan_detected_issues",
  "_synthetic_controller_issue_completion_snapshot",
  "_normalize_issue_record_to_controller_truth",
  "_refresh_issue_status_records_from_scan",
  "_clone_issue_status_records",
  "_build_realism_planner_issue_state",
  "_active_issue_codes_from_planner_issue_state",
  "_compact_realism_memo_for_trace",
  "_compact_resolution_summary_for_trace",
  "_compact_issue_codes",
  "_sanitize_realism_iteration_trace",
  "_issue_keys_from_status_records",
  "_issue_keys_requiring_iteration",
  "_filter_issue_status_records",
  "_controller_issue_effective_status",
  "_controller_issue_is_blocking",
  "_issue_needs_iteration",
  "_normalize_issue_record_to_controller_truth",
  "_iteration_decision_from_issue_record",
  "_controller_resolution_from_verification_issue",
  "_is_known_post_intake_issue_code",
  "_canonical_issue_title",
  "_normalize_realism_verifier_status",
  "_normalize_realism_materiality",
  "_normalize_realism_remaining_quarters",
  "_normalize_realism_lever_ids",
  "_issue_requires_remaining_horizon_scope",
  "_is_cash_pass_owned_issue_code",
  "_remaining_horizon_issue_quarters",
  "_issue_is_hard_issue",
  "_controller_issue_completion_snapshot",
  "_controller_issue_public_record",
  "_build_controller_issue_grade_summary",
  "_convergence_completion_policy_payload",
  "_metric_direction_hint",
  "_severity_minimum_change_pct",
  "_deterministic_lever_bound_value",
  "_metric_equilibrium_target",
  "_metric_target_zone",
  "_issue_impact_weight",
  "_issue_priority_map",
  "_compact_model_input_for_verification",
  "_build_realism_pass_consistency_context_payload",
  "_compact_current_cycle_packet_for_prompt",
  "_compact_issue_packets_for_prompt",
  "_build_unified_numeric_guidance_packet",
  "_build_strategy_resolved_issue_constraints",
  "_build_strategy_recheck_context_payload",
  "_touched_lever_ids_from_result",
  "_touched_issue_codes_from_result",
  "_normalized_issue_records",
  "_issue_ledger_key",
  "_core_issue_record",
  "_merge_issue_identity_fields",
  "_safe_int_in_range",
  "_completion_grade_letter",
  "_safe_divide",
  "_quarter_phase_label",
  "_issue_detail_blob",
  "_zone_repair_geometry",
  "_build_issue_metric_spec",
  "_table_target_currency_metric_spec",
  "_table_target_metric_id_set",
  "_is_table_target_metric_name",
  "_cost_structure_direct_metric_specs_for_quarter",
  "_issue_metric_specs_for_quarter",
  "_issue_metric_specs_for_record",
  "_issue_registry_entry",
  "_lever_catalog_entry_text",
  "_lever_catalog_entry_matches",
  "_repair_path_type_for_lever",
  "_driver_path_delta_bounds",
  "_repair_metric_delta_bounds",
  "_quarter_days_in_period",
  "_quarter_row_cost_of_goods_sold",
  "_quarter_row_operating_cost_base",
  "_component_delta_to_lever_delta",
  "_driver_target_conversion_context",
  "_metric_target_bounds_constrained_by_driver_scaffold",
  "_spillover_flags_for_metric",
  "_build_convergence_scorecard",
  "_repair_aware_issue_packets",
  "_sample_evenly_spaced_entries",
  "_driver_path_sort_key",
  "_select_focus_driver_paths",
  "_compact_driver_paths_for_prompt",
  "_compact_repair_targets_for_prompt",
  "_compact_repair_envelope_packets_for_prompt",
  "_compact_numeric_guidance_for_prompt",
  "_unified_target_fill_grid",
  "_locked_targets_by_quarter_response_template",
  "_unified_lever_control_fill_grid",
  "_full_horizon_model_input_repair_contract",
  "_model_input_repair_cell_schema",
  "_normalize_model_input_repair_cell_value",
  "_validate_and_normalize_model_input_repair_cells",
  "_exact_updates_from_model_input_repair_cells",
  "_convergence_issue_mapping_gate",
  "_lever_priority_tier",
  "_ordered_quarters_by_preference",
  "_build_deterministic_issue_packets",
  "_build_issue_packets_from_issue_ledger",
  "_numeric_solver_contract_issue_packet_map",
  "_numeric_solver_contract_baseline_quarter_map",
  "_numeric_adjust_actions_contract_error",
  "_normalize_unified_mapped_repair_targets",
  "_declared_mapped_target_metric_names",
  "_repair_target_direct_target_metric_names",
  "_merge_required_target_tolerances",
  "_augment_solver_quarter_target_metrics",
  "_issue_packet_mapped_driver_lever_ids",
  "_deterministic_guidance_focus_issue_codes",
  "_issue_packet_declared_target_metric_names",
  "_table_issue_candidate_lever_ids",
  "_raise_p_and_l_flatline_if_needed",
  "_build_capacity_support_issue_status_records",
  "_p_and_l_flatline_signals",
  "_build_p_and_l_flatline_issue_status_records",
  "_build_stage_maturity_cost_structure_issue_status_records",
  "_apply_realism_verification_to_issue_status_records",
]

# Legacy bound-name aliases — defined module-level so getattr in the
# binding system finds them. Each is a thin wrapper in legacy_compat.
from client_intake_and_finmo.post_intake_resolution_state.legacy_compat import (  # noqa: E402,F401
  _build_controller_resolution_state_from_issue_ledger,
  _build_realism_memo_from_issue_ledger,
  _build_resolution_summary_from_issue_ledger,
  _apply_realism_verification_to_issue_status_records,
  _controller_state_issue_status_records,
  _build_persisted_realism_memo_payload,
  _financial_story_issue_codes,
  _filter_cash_pass_owned_issue_records,
  _merge_new_scan_detected_issues,
  _synthetic_controller_issue_completion_snapshot,
  _normalize_issue_record_to_controller_truth,
  _refresh_issue_status_records_from_scan,
  _clone_issue_status_records,
  _build_realism_planner_issue_state,
  _active_issue_codes_from_planner_issue_state,
  _compact_realism_memo_for_trace,
  _compact_resolution_summary_for_trace,
  _compact_issue_codes,
  _sanitize_realism_iteration_trace,
  _issue_keys_from_status_records,
  _issue_keys_requiring_iteration,
  _filter_issue_status_records,
  _controller_issue_effective_status,
  _controller_issue_is_blocking,
  _issue_needs_iteration,
  _iteration_decision_from_issue_record,
  _controller_resolution_from_verification_issue,
  _is_known_post_intake_issue_code,
  _canonical_issue_title,
  _normalize_realism_verifier_status,
  _normalize_realism_materiality,
  _normalize_realism_remaining_quarters,
  _normalize_realism_lever_ids,
  _issue_requires_remaining_horizon_scope,
  _is_cash_pass_owned_issue_code,
  _remaining_horizon_issue_quarters,
  _issue_is_hard_issue,
  _controller_issue_completion_snapshot,
  _controller_issue_public_record,
  _build_controller_issue_grade_summary,
  _convergence_completion_policy_payload,
  _metric_direction_hint,
  _severity_minimum_change_pct,
  _deterministic_lever_bound_value,
  _metric_equilibrium_target,
  _metric_target_zone,
  _issue_impact_weight,
  _issue_priority_map,
  _compact_model_input_for_verification,
  _build_realism_pass_consistency_context_payload,
  _compact_current_cycle_packet_for_prompt,
  _compact_issue_packets_for_prompt,
  _build_unified_numeric_guidance_packet,
  _build_strategy_resolved_issue_constraints,
  _build_strategy_recheck_context_payload,
  _touched_lever_ids_from_result,
  _touched_issue_codes_from_result,
  _normalized_issue_records,
  _issue_ledger_key,
  _core_issue_record,
  _merge_issue_identity_fields,
  _safe_int_in_range,
  _completion_grade_letter,
  _safe_divide,
  _quarter_phase_label,
  _issue_detail_blob,
  _zone_repair_geometry,
  _build_issue_metric_spec,
  _table_target_currency_metric_spec,
  _table_target_metric_id_set,
  _is_table_target_metric_name,
  _cost_structure_direct_metric_specs_for_quarter,
  _issue_metric_specs_for_quarter,
  _issue_metric_specs_for_record,
  _issue_registry_entry,
  _lever_catalog_entry_text,
  _lever_catalog_entry_matches,
  _repair_path_type_for_lever,
  _driver_path_delta_bounds,
  _repair_metric_delta_bounds,
  _quarter_days_in_period,
  _quarter_row_cost_of_goods_sold,
  _quarter_row_operating_cost_base,
  _component_delta_to_lever_delta,
  _driver_target_conversion_context,
  _metric_target_bounds_constrained_by_driver_scaffold,
  _spillover_flags_for_metric,
  _build_convergence_scorecard,
  _repair_aware_issue_packets,
  _sample_evenly_spaced_entries,
  _driver_path_sort_key,
  _select_focus_driver_paths,
  _compact_driver_paths_for_prompt,
  _compact_repair_targets_for_prompt,
  _compact_repair_envelope_packets_for_prompt,
  _compact_numeric_guidance_for_prompt,
  _unified_target_fill_grid,
  _locked_targets_by_quarter_response_template,
  _unified_lever_control_fill_grid,
  _full_horizon_model_input_repair_contract,
  _model_input_repair_cell_schema,
  _normalize_model_input_repair_cell_value,
  _validate_and_normalize_model_input_repair_cells,
  _exact_updates_from_model_input_repair_cells,
  _convergence_issue_mapping_gate,
  _lever_priority_tier,
  _ordered_quarters_by_preference,
  _build_deterministic_issue_packets,
  _build_issue_packets_from_issue_ledger,
  _numeric_solver_contract_issue_packet_map,
  _numeric_solver_contract_baseline_quarter_map,
  _numeric_adjust_actions_contract_error,
  _normalize_unified_mapped_repair_targets,
  _declared_mapped_target_metric_names,
  _repair_target_direct_target_metric_names,
  _merge_required_target_tolerances,
  _augment_solver_quarter_target_metrics,
  _issue_packet_mapped_driver_lever_ids,
  _deterministic_guidance_focus_issue_codes,
  _issue_packet_declared_target_metric_names,
  _table_issue_candidate_lever_ids,
  _raise_p_and_l_flatline_if_needed,
  _build_capacity_support_issue_status_records,
  _p_and_l_flatline_signals,
  _build_p_and_l_flatline_issue_status_records,
  _build_stage_maturity_cost_structure_issue_status_records,
)
