INSERT INTO industry_types (naics_code, display_name) VALUES
('721', 'Accommodation'),
('72', 'Accommodation and Food Services'),
('561', 'Administrative and Support Services'),
('56', 'Administrative and Support and Waste Management and Remediation Services'),
('11', 'Agriculture, Forestry, Fishing and Hunting'),
('481', 'Air Transportation'),
('621', 'Ambulatory Health Care Services'),
('713', 'Amusement, Gambling, and Recreation Industries'),
('112', 'Animal Production'),
('315', 'Apparel Manufacturing'),
('71', 'Arts, Entertainment, and Recreation'),
('312', 'Beverage and Tobacco Product Manufacturing'),
('515', 'Broadcasting (except Internet)'),
('444', 'Building Material and Garden Equipment and Supplies Dealers'),
('325', 'Chemical Manufacturing'),
('448', 'Clothing and Clothing Accessories Stores'),
('334', 'Computer and Electronic Product Manufacturing'),
('23', 'Construction'),
('236', 'Construction of Buildings'),
('492', 'Couriers and Messengers'),
('522', 'Credit Intermediation and Related Activities'),
('111', 'Crop Production'),
('518', 'Data Processing, Hosting, and Related Services'),
('61', 'Educational Services'),
('335', 'Electrical Equipment, Appliance, and Component Manufacturing'),
('443', 'Electronics and Appliance Stores'),
('332', 'Fabricated Metal Product Manufacturing'),
('52', 'Finance and Insurance'),
('114', 'Fishing, Hunting and Trapping'),
('311', 'Food Manufacturing'),
('722', 'Food Services and Drinking Places'),
('445', 'Food and Beverage Stores'),
('113', 'Forestry and Logging'),
('525', 'Funds, Trusts, and Other Financial Vehicles'),
('442', 'Furniture and Home Furnishings Stores'),
('337', 'Furniture and Related Product Manufacturing'),
('447', 'Gasoline Stations'),
('452', 'General Merchandise Stores'),
('62', 'Health Care and Social Assistance'),
('446', 'Health and Personal Care Stores'),
('237', 'Heavy and Civil Engineering Construction'),
('622', 'Hospitals'),
('51', 'Information'),
('524', 'Insurance Carriers and Related Activities'),
('516', 'Internet Publishing and Broadcasting'),
('316', 'Leather and Allied Product Manufacturing'),
('533', 'Lessors of Nonfinancial Intangible Assets (except Copyrighted Works)'),
('333', 'Machinery Manufacturing'),
('55', 'Management of Companies and Enterprises'),
('31-33', 'Manufacturing'),
('423', 'Merchant Wholesalers, Durable Goods'),
('424', 'Merchant Wholesalers, Nondurable Goods'),
('212', 'Mining (except Oil and Gas)'),
('21', 'Mining, Quarrying, and Oil and Gas Extraction'),
('339', 'Miscellaneous Manufacturing'),
('453', 'Miscellaneous Store Retailers'),
('521', 'Monetary Authorities - Central Bank'),
('512', 'Motion Picture and Sound Recording Industries'),
('441', 'Motor Vehicle and Parts Dealers'),
('712', 'Museums, Historical Sites, and Similar Institutions'),
('327', 'Nonmetallic Mineral Product Manufacturing'),
('454', 'Nonstore Retailers'),
('623', 'Nursing and Residential Care Facilities'),
('211', 'Oil and Gas Extraction'),
('519', 'Other Information Services'),
('81', 'Other Services (except Public Administration)'),
('322', 'Paper Manufacturing'),
('711', 'Performing Arts, Spectator Sports, and Related Industries'),
('812', 'Personal and Laundry Services'),
('324', 'Petroleum and Coal Products Manufacturing'),
('486', 'Pipeline Transportation'),
('326', 'Plastics and Rubber Products Manufacturing'),
('491', 'Postal Service'),
('331', 'Primary Metal Manufacturing'),
('323', 'Printing and Related Support Activities'),
('814', 'Private Households'),
('54', 'Professional, Scientific, and Technical Services'),
('511', 'Publishing Industries (except Internet)'),
('482', 'Rail Transportation'),
('531', 'Real Estate'),
('53', 'Real Estate and Rental and Leasing'),
('813', 'Religious, Grantmaking, Civic, Professional, and Similar Organizations'),
('532', 'Rental and Leasing Services'),
('811', 'Repair and Maintenance'),
('44-45', 'Retail Trade'),
('487', 'Scenic and Sightseeing Transportation'),
('523', 'Securities, Commodity Contracts, and Other Financial Investments and Related Activities'),
('624', 'Social Assistance'),
('238', 'Specialty Trade Contractors'),
('451', 'Sporting Goods, Hobby, Book, and Music Stores'),
('115', 'Support Activities for Agriculture and Forestry'),
('213', 'Support Activities for Mining'),
('488', 'Support Activities for Transportation'),
('517', 'Telecommunications'),
('313', 'Textile Mills'),
('314', 'Textile Product Mills'),
('485', 'Transit and Ground Passenger Transportation'),
('336', 'Transportation Equipment Manufacturing'),
('48-49', 'Transportation and Warehousing'),
('484', 'Truck Transportation'),
('22', 'Utilities'),
('493', 'Warehousing and Storage'),
('562', 'Waste Management and Remediation Services'),
('483', 'Water Transportation'),
('425', 'Wholesale Electronic Markets and Agents and Brokers'),
('42', 'Wholesale Trade'),
('321', 'Wood Product Manufacturing');
