// Usage: node render_plan.js bundle.json plan.json chartsdir out.docx [subtitle]
const fs=require('fs'), path=require('path');
const D=require('docx');
const {Document,Packer,Paragraph,TextRun,HeadingLevel,Table,TableRow,TableCell,WidthType,AlignmentType,ImageRun,PageBreak,TableOfContents,Header,Footer,PageNumber,ShadingType,BorderStyle,PageOrientation}=D;
const [bundlePath,planPath,chartsDir,outPath,subtitle]=process.argv.slice(2);
const bundle=JSON.parse(fs.readFileSync(bundlePath)); const plan=JSON.parse(fs.readFileSync(planPath));
const sizes=JSON.parse(fs.readFileSync(path.join(chartsDir,'sizes.json')));
const FONT_BODY='Georgia',FONT_HEAD='Calibri',NAVY='1F3A5F';
const fmt0=v=>(v<0?'(':'')+'$'+Math.abs(Math.round(v)).toLocaleString('en-US')+(v<0?')':''); const pct1=v=>(v*100).toFixed(1)+'%';
function runs(text,base={}){const out=[];const re=/(\[\^\d+\]|\*\*[^*]+\*\*)/g;let last=0,m;while((m=re.exec(text))){if(m.index>last)out.push(new TextRun({text:text.slice(last,m.index),font:FONT_BODY,size:22,...base}));const t=m[0];if(t.startsWith('[^'))out.push(new TextRun({text:t.slice(2,-1),superScript:true,font:FONT_BODY,size:22,...base}));else out.push(new TextRun({text:t.slice(2,-2),bold:true,font:FONT_BODY,size:22,...base}));last=m.index+t.length;}if(last<text.length)out.push(new TextRun({text:text.slice(last),font:FONT_BODY,size:22,...base}));return out;}
const P=(t,base)=>new Paragraph({children:runs(t,base||{}),spacing:{after:160,line:300},alignment:AlignmentType.JUSTIFIED});
const H1=(t,pb=true)=>new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:t,font:FONT_HEAD,size:32,bold:true,color:NAVY})],spacing:{before:360,after:200},pageBreakBefore:pb});
const H2=t=>new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun({text:t,font:FONT_HEAD,size:26,bold:true,color:NAVY})],spacing:{before:280,after:120}});
const Cap=t=>new Paragraph({children:[new TextRun({text:t,font:FONT_HEAD,size:18,italics:true,color:'555555'})],spacing:{after:240}});
const Note=t=>new Paragraph({children:runs(t,{size:18,color:'444444'}),spacing:{after:60,line:240}});
function Tbl(headers,rows,widths,size=17,boldFirst=false){const total=widths.reduce((a,b)=>a+b,0);const cell=(t,i,hdr,shade)=>new TableCell({width:{size:widths[i],type:WidthType.DXA},shading:hdr?{fill:'E8EDF3',type:ShadingType.CLEAR,color:'auto'}:(shade?{fill:'F5F7FA',type:ShadingType.CLEAR,color:'auto'}:undefined),borders:{top:{style:BorderStyle.SINGLE,size:hdr?8:2,color:hdr?NAVY:'CCCCCC'},bottom:{style:BorderStyle.SINGLE,size:hdr?8:2,color:hdr?NAVY:'CCCCCC'},left:{style:BorderStyle.NONE,size:0,color:'FFFFFF'},right:{style:BorderStyle.NONE,size:0,color:'FFFFFF'}},margins:{top:50,bottom:50,left:80,right:80},children:[new Paragraph({children:[new TextRun({text:String(t??''),font:FONT_HEAD,size,bold:hdr||(boldFirst&&i===0)})],alignment:i===0?AlignmentType.LEFT:AlignmentType.RIGHT})]});return new Table({width:{size:total,type:WidthType.DXA},columnWidths:widths,rows:[new TableRow({tableHeader:true,children:headers.map((h,i)=>cell(h,i,true))}),...rows.map((r,ri)=>new TableRow({children:r.map((c,i)=>cell(c,i,false,ri%2===1))}))]});}
let figN=0,tabN=0;
function Fig(id,captionPrefix){const f=path.join(chartsDir,id+'.png');if(!fs.existsSync(f))return[];figN++;const w=6.3,h=(sizes[id]||3.4)*(w/7.2);return[new Paragraph({children:[new ImageRun({type:'png',data:fs.readFileSync(f),transformation:{width:w*96,height:h*96}})],spacing:{before:120,after:60},alignment:AlignmentType.CENTER}),Cap(`Figure ${figN} — ${captionPrefix}`)];}
const A=bundle.model.annual,Y=A.map(r=>`Year ${r.year}`),hdrs=['',...Y],W6=[2600,1450,1450,1450,1450,1450];
const rowOf=(l,k,f=fmt0)=>[l,...A.map(r=>f(r[k]))],rowFn=(l,fn)=>[l,...A.map(r=>fn(r))];
const dsSched=r=>r.interest+(bundle.record.financials.annual_principal_payment||0)+(r.lease_principal_repayments||0);
const TABLES={
 income_statement_annual:()=>[Tbl(hdrs,[rowOf('Revenue','revenue'),rowOf('Cost of goods sold','cost_of_goods_sold'),rowOf('Gross profit','gross_profit'),rowFn('  Gross margin',r=>pct1(r.gross_profit/r.revenue)),rowOf('Payroll','payroll'),rowOf('Rent','lease_rent'),rowOf('Marketing','marketing'),rowOf('General and administrative','general_and_administrative'),rowOf('EBITDA','ebitda'),rowFn('  EBITDA margin',r=>pct1(r.ebitda/r.revenue)),rowOf('Depreciation','depreciation'),rowOf('Interest','interest'),rowOf('Taxes','taxes'),rowOf('Net income','net_income'),rowFn('  Net margin',r=>pct1(r.net_income/r.revenue))],W6),'Projected income statement, Years 1–5 (fiscal years ending September)'],
 balance_sheet_annual:()=>[Tbl(hdrs,[rowOf('Cash','cash'),rowOf('Accounts receivable','accounts_receivable'),rowOf('Inventory','inventory'),rowOf('Property and equipment, net','ppe'),rowOf('Total assets','total_assets'),rowOf('Accounts payable','accounts_payable'),rowFn('Term debt',r=>fmt0(r.debt_closing_balance)),rowFn('Equipment leases',r=>fmt0(r.lease_closing_balance_total||0)),rowOf('Total liabilities','total_liabilities'),rowOf("Owner's equity",'total_equity')],W6),'Projected balance sheet at each fiscal year-end'],
 cash_flow_annual:()=>[Tbl(hdrs,[rowOf('Operating cash flow','operating_cash_flow'),rowFn('Capital expenditures',r=>fmt0(-r.capital_expenditures)),rowFn('New borrowing',r=>fmt0(r.debt_issuance||0)),rowFn('Term-debt repayment',r=>fmt0(-r.debt_repayment)),rowFn('Lease principal',r=>fmt0(-(r.lease_principal_repayments||0))),rowFn('Owner distributions',r=>fmt0(-r.owner_distributions)),rowOf('Year-end cash','cash')],W6),'Projected cash flow, Years 1–5'],
 key_ratios:()=>[Tbl(hdrs,[['Debt-service coverage (EBITDA ÷ scheduled service)',...A.map(r=>r.debt_closing_balance>0||r.debt_repayment>0?(r.ebitda/dsSched(r)).toFixed(1)+'×':'no term debt')],rowFn('Payroll as % of revenue',r=>pct1(r.payroll/r.revenue)),rowFn('Receivables, days of revenue',r=>Math.round(r.accounts_receivable/r.revenue*365)),rowFn('Inventory, days of cost of goods',r=>Math.round(r.inventory/r.cost_of_goods_sold*365)),rowFn('Cash, months of operating cost',r=>(r.cash/((r.cost_of_goods_sold+r.payroll+r.lease_rent+r.marketing+r.general_and_administrative)/12)).toFixed(1)),rowFn(`Revenue per employee (${bundle.record.financials.current_num_employees} people)`,r=>fmt0(r.revenue/bundle.record.financials.current_num_employees))],W6),'Key ratios; scheduled debt service is interest plus stated annual principal plus lease principal'],
 // a table with nothing in it does not render (2026-09-08): an all-zero debt
 // schedule in a no-debt plan is the phantom-roles class
 debt_schedule:()=>{const live=bundle.model.debt_schedule.some(r=>(r.opening_debt||0)>0||(r.closing_debt||0)>0||(r.actual_debt_issuance||0)>0||(r.actual_debt_repayment||0)>0||(r.interest_expense||0)>0);if(!live)return null;const rows=bundle.model.debt_schedule.filter((r,i)=>i<12||r.closing_debt>0).slice(0,12).map(r=>['Q'+r.quarter_index+'  '+r.date,fmt0(r.opening_debt),fmt0(r.actual_debt_issuance||0),fmt0(r.actual_debt_repayment),fmt0(r.interest_expense),fmt0(r.closing_debt)]);return[Tbl(['Quarter','Opening','New borrowing','Principal paid','Interest','Closing'],rows,[2200,1500,1500,1500,1300,1500]),'Term-loan schedule by quarter'];},
};
const REG=JSON.parse(fs.readFileSync(process.env.FIGURE_REGISTRY||'figure_registry.json','utf8')).items;
const REPORT=[];
let FIGSTATUS={};try{FIGSTATUS=JSON.parse(fs.readFileSync(path.join(chartsDir,'figures_report.json'),'utf8'));}catch(e){}
function renderItem(it){const out=[];if(it.kind==='figure'){if(fs.existsSync(`${chartsDir}/${it.id}.png`)){out.push(...Fig(it.id,it.caption||it.id.replace(/_/g,' ')));REPORT.push({id:it.id,kind:'figure',placed:true});}else{const st=FIGSTATUS[it.id];REPORT.push({id:it.id,kind:'figure',placed:false,reason:st&&st.reason?st.reason:''});}}else if(it.kind==='table'){const t=TABLES[it.id];if(t){const res=t();if(res){const[tbl,cap]=res;tabN++;out.push(tbl,Cap(`Table ${tabN} — ${it.caption||cap}.`));REPORT.push({id:it.id,kind:'table',placed:true});}else{REPORT.push({id:it.id,kind:'table',placed:false,reason:'data condition not met (all-empty table)'});}}else{REPORT.push({id:it.id,kind:'table',placed:false,reason:''});}}return out;}
function blocks(sec){
 // writer blocks only: paragraph, subheading, table_inline. Figures/tables come from the registry; any the writer supplied are ignored.
 const items=REG.filter(it=>it.section===sec.key);
 const bl=sec.blocks.filter(b=>['paragraph','subheading','table_inline'].includes(b.type));
 const out=[];let paraN=0,curSub=null;
 const flushSub=()=>{if(curSub!==null)for(const it of items.filter(i=>i.anchor.toLowerCase()===('end_of_subsection:'+curSub).toLowerCase()))out.push(...renderItem(it));};
 for(const b of bl){
  if(b.type==='subheading'){flushSub();curSub=b.text.trim();out.push(H2(b.text));}
  else if(b.type==='paragraph'){out.push(P(b.text));paraN++;for(const it of items.filter(i=>i.anchor==='after_paragraph:'+paraN))out.push(...renderItem(it));}
  else if(b.type==='table_inline'&&b.headers&&b.rows){const n=b.headers.length;const first=Math.min(3200,Math.round(9360*0.32));const rest=Math.floor((9360-first)/(n-1||1));const widths=n===1?[9360]:[first,...Array(n-1).fill(rest)];tabN++;out.push(Tbl(b.headers,b.rows.map(r=>r.map(x=>x??'')),widths,16,true),Cap(`Table ${tabN} — ${b.caption||''}`));}
 }
 flushSub();
 for(const it of items.filter(i=>i.anchor==='end'))out.push(...renderItem(it));
 // anchors that never matched (short section, missing subheading) fall to the end
 const placed=new Set();for(const it of items){const a=it.anchor;if(a==='end')placed.add(it.id);if(a.startsWith('after_paragraph:')&&parseInt(a.split(':')[1])<=paraN)placed.add(it.id);if(a.startsWith('end_of_subsection:')&&bl.some(b=>b.type==='subheading'&&b.text.trim().toLowerCase()===a.split(':')[1].toLowerCase()))placed.add(it.id);}
 for(const it of items.filter(i=>!placed.has(i.id)))out.push(...renderItem(it));
 return out;}
const order=['executive_summary','the_business','products_and_services','market_and_industry','competitive_landscape','marketing_and_sales','operations','management_team','staffing_and_human_capital','financial_plan','risks_and_mitigations','funding_request','disclosures','sources_and_notes'];
const secs=order.map(k=>plan.sections.find(s=>s.key===k)).filter(Boolean);
const body=[];let n=0;
for(const s of secs){if(s.key!=="sources_and_notes"&&!(s.blocks||[]).length)continue;const numbered=!['executive_summary','sources_and_notes'].includes(s.key);if(numbered)n++;body.push(H1((numbered?`${n}. `:'')+s.title));if(s.key==='sources_and_notes'){for(const nt of plan.notes||[])body.push(Note(`**${nt.id}.** ${nt.text}`));body.push(...blocks(s));}else body.push(...blocks(s));}
if(!secs.find(s=>s.key==='sources_and_notes')&&(plan.notes||[]).length){body.push(H1('Sources & Notes'));for(const nt of plan.notes)body.push(Note(`**${nt.id}.** ${nt.text}`));}
// appendix (assembled)
const Q=bundle.model.quarters||[];const app=[];
app.push(H1('Appendix',false));
if(Q.length){const qh=['',...Q.map(q=>'Q'+q.quarter_index)],wq=[1900,...Q.map(()=>560)],qrow=(l,k)=>[l,...Q.map(q=>Math.round((q[k]||0)/1000).toLocaleString())];app.push(H2('A. Quarterly financial statements ($ thousands)'));app.push(Tbl(qh,[qrow('Revenue','revenue'),qrow('Cost of goods sold','cost_of_goods_sold'),qrow('Gross profit','gross_profit'),qrow('Payroll','payroll'),qrow('Rent','lease_rent'),qrow('Marketing','marketing'),qrow('G&A','general_and_administrative'),qrow('EBITDA','ebitda'),qrow('Depreciation','depreciation'),qrow('Interest','interest'),qrow('Taxes','taxes'),qrow('Net income','net_income')],wq,13),Cap('Table A1 — Income statement by quarter.'));app.push(Tbl(qh,[qrow('Cash','cash'),qrow('Receivables','accounts_receivable'),qrow('Inventory','inventory'),qrow('Total assets','total_assets'),qrow('Payables','accounts_payable'),qrow('Term debt','debt_closing_balance'),qrow('Total liabilities','total_liabilities'),qrow("Owner's equity",'total_equity')],wq,13),Cap('Table A2 — Balance sheet at quarter-end.'));app.push(Tbl(qh,[qrow('Operating cash flow','operating_cash_flow'),qrow('Capital expenditures','capital_expenditures'),qrow('New borrowing','debt_issuance'),qrow('Debt repayment','debt_repayment'),qrow('Distributions','owner_distributions')],wq,13),Cap('Table A3 — Cash flow items by quarter.'));}
// bundle.model.acceptance is deleted by the v2 strip (bundle.py: "an
// assembler-authored operator note"), so this printed the literal
// "undefined" on every plan. Deleted rather than restored (Nick
// 2026-09-10): "18/18 structural checks passed" is a machinery
// reference, and the document never refers to what checked it.
app.push(H2('B. Record'));app.push(Note(`Planning run ${bundle.meta.planning_run_id} · draft ${bundle.meta.draft_id} · projections ${bundle.meta.projection_start} to ${bundle.meta.projection_end} · bundle prepared ${bundle.meta.bundle_prepared}.`));
const secProps={page:{size:{width:12240,height:15840},margin:{top:1440,bottom:1296,left:1440,right:1440}}};
const header=new Header({children:[new Paragraph({children:[new TextRun({text:`${bundle.meta.business_name} — Business Plan`,font:FONT_HEAD,size:16,color:'777777'})],alignment:AlignmentType.RIGHT})]});
const footer=new Footer({children:[new Paragraph({children:[new TextRun({text:'Confidential · Page ',font:FONT_HEAD,size:16,color:'777777'}),new TextRun({children:[PageNumber.CURRENT],font:FONT_HEAD,size:16,color:'777777'}),new TextRun({text:' of ',font:FONT_HEAD,size:16,color:'777777'}),new TextRun({children:[PageNumber.TOTAL_PAGES],font:FONT_HEAD,size:16,color:'777777'}),new TextRun({text:' · Prepared September 2026 · v1.0',font:FONT_HEAD,size:16,color:'777777'})],alignment:AlignmentType.CENTER})]});
const cover=[new Paragraph({spacing:{before:4000}}),new Paragraph({children:[new TextRun({text:bundle.meta.business_name,font:FONT_HEAD,size:56,bold:true,color:NAVY})],spacing:{after:200}}),new Paragraph({children:[new TextRun({text:'Business Plan',font:FONT_HEAD,size:36,color:'444444'})],spacing:{after:120}}),new Paragraph({children:[new TextRun({text:subtitle||'Five-year operating and financial plan',font:FONT_BODY,size:24,italics:true,color:'555555'})],spacing:{after:1600}}),new Paragraph({children:[new TextRun({text:`${bundle.record.operating_model.geographic_coverage?'':''}Prepared September 2026`,font:FONT_BODY,size:22})]}),new Paragraph({children:[new TextRun({text:'This plan accompanies a 16-sheet financial model. Figures in this document are drawn from that model and from the sources listed in Sources & Notes; quarterly detail, the valuation and what-if scenarios are held in the model.',font:FONT_BODY,size:18,color:'666666'})],spacing:{before:2400}})];
const doc=new Document({styles:{default:{document:{run:{font:FONT_BODY,size:22}}},paragraphStyles:[{id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font:FONT_HEAD,size:32,bold:true,color:NAVY},paragraph:{spacing:{before:360,after:200},outlineLevel:0}},{id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{font:FONT_HEAD,size:26,bold:true,color:NAVY},paragraph:{spacing:{before:280,after:120},outlineLevel:1}}]},features:{updateFields:true},sections:[{properties:{...secProps,titlePage:true},headers:{default:header},footers:{default:footer},children:[...cover,new Paragraph({children:[new PageBreak()]}),new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:'Contents',font:FONT_HEAD,size:32,bold:true,color:NAVY})]}),new TableOfContents('Contents',{hyperlink:true,headingStyleRange:'1-2'}),...body]},{properties:{page:{size:{width:12240,height:15840,orientation:PageOrientation.LANDSCAPE},margin:{top:1080,bottom:1080,left:1080,right:1080}}},headers:{default:header},footers:{default:footer},children:app}]});
Packer.toBuffer(doc).then(buf=>{fs.writeFileSync(outPath,buf);
for(const it of REG){if(!REPORT.some(r=>r.id===it.id)){REPORT.push({id:it.id,kind:it.kind,placed:false,reason:plan.sections.some(s=>s.key===it.section)?'':'section not in plan (omitted)'});}}
fs.writeFileSync(outPath+'.render_report.json',JSON.stringify(REPORT,null,1));console.log('written',outPath,buf.length,'figures',figN,'tables',tabN);});
