"""Post-intake fail-fast authority."""

from __future__ import annotations

from .fail_fast import (
  CASH_STRATEGY_TEST_MODE_FAIL_FLAGS,
  BUSINESS_SHAPE_TEST_MODE_FAIL_FLAGS,
  CONVERGENCE_TEST_MODE_FAIL_FLAGS,
  GLOBAL_POST_INTAKE_TEST_MODE_FAIL_FLAGS,
  PAYROLL_HEADCOUNT_TEST_MODE_FAIL_FLAGS,
  POST_INTAKE_FAIL_FAST_ENV,
  TRANSLATION_TEST_MODE_FAIL_FLAGS,
  assert_post_intake_cash_buffer_integrity,
  assert_marketing_presence_applied,
  assert_post_intake_business_shape_applied,
  assert_post_intake_finmo_statement_integrity,
  assert_post_intake_global_invariants,
  assert_post_intake_horizon_integrity,
  assert_post_intake_model_input_rows_integrity,
  assert_post_intake_rebuilt_finmo_matches_model_input,
  assert_post_intake_revenue_driver_integrity,
  assert_post_intake_schedule_markers_integrity,
  assert_stage_ramp_expense_path_applied,
  assert_stage_ramp_revenue_path_applied,
  post_intake_convergence_test_mode_enabled,
  post_intake_fail_fast_enabled,
  post_intake_fail_fast_raise,
  post_intake_fail_fast_result,
)

__all__ = [
  "CASH_STRATEGY_TEST_MODE_FAIL_FLAGS",
  "BUSINESS_SHAPE_TEST_MODE_FAIL_FLAGS",
  "CONVERGENCE_TEST_MODE_FAIL_FLAGS",
  "GLOBAL_POST_INTAKE_TEST_MODE_FAIL_FLAGS",
  "PAYROLL_HEADCOUNT_TEST_MODE_FAIL_FLAGS",
  "POST_INTAKE_FAIL_FAST_ENV",
  "TRANSLATION_TEST_MODE_FAIL_FLAGS",
  "assert_post_intake_cash_buffer_integrity",
  "assert_marketing_presence_applied",
  "assert_post_intake_business_shape_applied",
  "assert_post_intake_finmo_statement_integrity",
  "assert_post_intake_global_invariants",
  "assert_post_intake_horizon_integrity",
  "assert_post_intake_model_input_rows_integrity",
  "assert_post_intake_rebuilt_finmo_matches_model_input",
  "assert_post_intake_revenue_driver_integrity",
  "assert_post_intake_schedule_markers_integrity",
  "assert_stage_ramp_expense_path_applied",
  "assert_stage_ramp_revenue_path_applied",
  "post_intake_convergence_test_mode_enabled",
  "post_intake_fail_fast_enabled",
  "post_intake_fail_fast_raise",
  "post_intake_fail_fast_result",
]
