# -*- coding: utf-8 -*-
"""CAPTURE THE RUN ARTIFACTS R32 NEEDS, ONCE, AS A FROZEN FIXTURE.

WHY THIS EXISTS. R32 hashes the workbook FORMULA GRID built from a real
payload. The workbook builder's consumer-side boundary gate validates five
JSON payloads, and two of them - payroll_headcount and debt_schedule - are
RUN artifacts: payroll_headcount is authored by GPT during the planning run
(gpt_payroll_author.py), so nothing offline can derive it.

Three ways to feed it, and only one is honest:

  live DB read   - breaks determinism. The row can change between the
                   baseline run and the current run of the same prove, and a
                   golden master whose input moves produces a false DRIFT,
                   which is the one false alarm that costs the gate its
                   credibility.
  synthesized    - drifts against the 15-field contract. A stub that
                   satisfies today's validator tests the stub, not the
                   workbook, and silently stops matching the real shape.
  FROZEN FIXTURE - capture the real artifact once, pin it, hash the workbook
                   built from it. The input never moves; the OUTPUT is what
                   is under test.

This script does the capture. Run it ONCE on a machine with DB access:

    python "Test Files/_capture_workbook_fixture.py" 6feac758
    python "Test Files/_capture_workbook_fixture.py" plcogs43

It writes replay_gate/_run_artifacts.py - a plain module of literals with
provenance (draft, run, stage, capture date, per-payload sha256). Commit it.
Re-run only when the payload CONTRACT changes, never to "refresh" the data:
refreshing is what turns a frozen fixture back into a moving input.
"""
import hashlib
import io
import json
import os
import pprint
import sys

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
from dotenv import load_dotenv

load_dotenv()
import mysql.connector

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
OUT = os.path.join(REPO, "replay_gate", "_run_artifacts.py")

prefix = sys.argv[1] if len(sys.argv) > 1 else "6feac758"

conn = mysql.connector.connect(
    host=os.getenv("MYSQL_HOST"), user=os.getenv("MYSQL_USER"),
    password=os.getenv("MYSQL_PASSWORD"), database=os.getenv("MYSQL_DB"),
    port=int(os.getenv("MYSQL_PORT") or 3306), autocommit=True,
)
cur = conn.cursor(dictionary=True)
cur.execute(
    "SELECT draft_id, client_id, operating_model_json, payroll_headcount, "
    "debt_schedule FROM intake_consult_drafts WHERE draft_id LIKE %s LIMIT 1",
    (prefix + "%",))
row = cur.fetchone()
if not row:
    print(f"NO DRAFT matching {prefix}")
    sys.exit(1)

draft_id = row["draft_id"]
cur.execute(
    "SELECT planning_run_id FROM planning_runs WHERE draft_id=%s "
    "ORDER BY created_at DESC LIMIT 1", (draft_id,))
run_id = (cur.fetchone() or {}).get("planning_run_id")
stage = ""
planning_run_json = {}
if run_id:
    cur.execute(
        "SELECT stage, planning_run_json FROM planning_run_checkpoints "
        "WHERE planning_run_id=%s AND finmo_json IS NOT NULL "
        "ORDER BY created_at DESC LIMIT 1", (run_id,))
    ck = cur.fetchone() or {}
    stage = str(ck.get("stage") or "")
    raw = ck.get("planning_run_json")
    if raw:
        planning_run_json = json.loads(raw) if isinstance(raw, str) else dict(raw)


def _obj(raw):
    if raw is None:
        return {}
    if isinstance(raw, (str, bytes)):
        try:
            return json.loads(raw or "{}")
        except Exception:
            return {}
    return dict(raw)


payroll = _obj(row.get("payroll_headcount"))
debt = _obj(row.get("debt_schedule"))

# REFUSE TO PIN AN EMPTY ARTIFACT. A fixture of {} satisfies nothing and
# would let R32 hash a workbook built from a hollow payload - stable, and
# meaningless. Better to fail here and pick a draft that has actually run.
problems = []
if not payroll:
    problems.append("payroll_headcount is empty - this draft has not been "
                    "through a planning run, so GPT never authored it")
if not debt:
    problems.append("debt_schedule is empty")
if problems:
    print(f"REFUSING to write a hollow fixture for {draft_id}:")
    for p in problems:
        print("  - " + p)
    print("Pick a draft with a completed run (the same rows the byte-floor "
          "script reads), e.g. 6feac758 or plcogs43.")
    sys.exit(2)


def _sha(payload):
    return hashlib.sha256(json.dumps(
        payload, sort_keys=True, separators=(",", ":"),
        default=str).encode("utf-8")).hexdigest()


body = f'''# -*- coding: utf-8 -*-
"""FROZEN RUN ARTIFACTS - captured once, never refreshed.

Generated by Test Files/_capture_workbook_fixture.py. These are REAL
payloads from a completed planning run: payroll_headcount is GPT-authored
during the run (gpt_payroll_author.py) and cannot be derived offline, so R32
pins the real thing rather than reading the DB live (which would break
determinism) or synthesizing a stub (which would drift against the contract
and test nothing).

DO NOT "refresh" this file to pick up newer data. Refreshing turns a frozen
fixture back into a moving input, and a golden master over a moving input
produces false DRIFT. Re-capture ONLY when the payload contract changes.

  draft            {draft_id}
  planning run     {run_id}
  checkpoint stage {stage or "(none)"}
  payroll_headcount sha256  {_sha(payroll)}
  debt_schedule     sha256  {_sha(debt)}
  planning_run_json sha256  {_sha(planning_run_json)}
"""

PROVENANCE = {{
    "draft_id": {draft_id!r},
    "planning_run_id": {str(run_id)!r},
    "stage": {stage!r},
}}

PAYROLL_HEADCOUNT = {pprint.pformat(payroll, width=78)}

DEBT_SCHEDULE = {pprint.pformat(debt, width=78)}

PLANNING_RUN_JSON = {pprint.pformat(planning_run_json, width=78)}
'''

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write(body)

print(f"wrote {OUT}")
print(f"  draft {draft_id} | run {str(run_id)[:14]} | stage {stage}")
print(f"  payroll_headcount {len(json.dumps(payroll, default=str)):,} bytes "
      f"sha {_sha(payroll)[:16]}")
print(f"  debt_schedule     {len(json.dumps(debt, default=str)):,} bytes "
      f"sha {_sha(debt)[:16]}")
print("commit it, then re-run --prove; R32 will hash the workbook built "
      "from these.")
